name: PR Staging deploy

on:
  workflow_dispatch

env:
  ENV: staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: echo running on branch ${GITHUB_REF##*/}
