name: PR Staging deploy

on:
  workflow_dispatch:
    inputs:
      desc:
        description: "Select PR branch to deploy..."

env:
  ENV: staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: echo running on branch ${{ github.ref_name }}
