name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      git_tag:
        description: 'Git tag to which it is deployed'
        default: 'v1.0.0'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.STAGING_DEPLOY_KEY }}

    - run: ./scripts/live_deploy ${{ github.event.inputs.git_tag }}"
