name: Staging deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
        env:
          DEPLOY_USER: ${{ vars.DEPLOY_USER }}
      - run: echo "DEPLOY_USER: $DEPLOY_USER"
      #- run: ./scripts/stage
