name: Staging deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  # Setting an environment variable with the value of a configuration variable
  DEPLOY_USER: ${{ vars.DEPLOY_USER }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - run: ./scripts/stage
